project:
  type: website

website:
  title: "Guilherme Rodrigues"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Guiermis
      - icon: linkedin
        href: https://www.linkedin.com/in/guilherme-oliveira-975767213/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

