project:
  type: website
  output-dir: docs

website:
  title: "Guilherme Rodrigues"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Guiermis
      - icon: linkedin
        href: https://www.linkedin.com/in/guilherme-oliveira-975767213/
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle:
      caption: "🌙"
    css: styles.css

editor: visual

